/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CabinetRouteImport } from './routes/cabinet'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as CreateRouteImport } from './routes/create'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as RidesRouteImport } from './routes/rides'
import { Route as OrderMatchIdRouteImport } from './routes/order.$matchId'
import { Route as ListingKindIdRouteImport } from './routes/listing.$kind.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CabinetRoute = CabinetRouteImport.update({
  id: '/cabinet',
  path: '/cabinet',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RidesRoute = RidesRouteImport.update({
  id: '/rides',
  path: '/rides',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderMatchIdRoute = OrderMatchIdRouteImport.update({
  id: '/order/$matchId',
  path: '/order/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingKindIdRoute = ListingKindIdRouteImport.update({
  id: '/listing/$kind/$id',
  path: '/listing/$kind/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cabinet': typeof CabinetRoute
  '/chats': typeof ChatsRoute
  '/create': typeof CreateRoute
  '/leaderboard': typeof LeaderboardRoute
  '/rides': typeof RidesRoute
  '/order/$matchId': typeof OrderMatchIdRoute
  '/listing/$kind/$id': typeof ListingKindIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cabinet': typeof CabinetRoute
  '/chats': typeof ChatsRoute
  '/create': typeof CreateRoute
  '/leaderboard': typeof LeaderboardRoute
  '/rides': typeof RidesRoute
  '/order/$matchId': typeof OrderMatchIdRoute
  '/listing/$kind/$id': typeof ListingKindIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cabinet': typeof CabinetRoute
  '/chats': typeof ChatsRoute
  '/create': typeof CreateRoute
  '/leaderboard': typeof LeaderboardRoute
  '/rides': typeof RidesRoute
  '/order/$matchId': typeof OrderMatchIdRoute
  '/listing/$kind/$id': typeof ListingKindIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cabinet'
    | '/chats'
    | '/create'
    | '/leaderboard'
    | '/rides'
    | '/order/$matchId'
    | '/listing/$kind/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cabinet'
    | '/chats'
    | '/create'
    | '/leaderboard'
    | '/rides'
    | '/order/$matchId'
    | '/listing/$kind/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/cabinet'
    | '/chats'
    | '/create'
    | '/leaderboard'
    | '/rides'
    | '/order/$matchId'
    | '/listing/$kind/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CabinetRoute: typeof CabinetRoute
  ChatsRoute: typeof ChatsRoute
  CreateRoute: typeof CreateRoute
  LeaderboardRoute: typeof LeaderboardRoute
  RidesRoute: typeof RidesRoute
  OrderMatchIdRoute: typeof OrderMatchIdRoute
  ListingKindIdRoute: typeof ListingKindIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabinet': {
      id: '/cabinet'
      path: '/cabinet'
      fullPath: '/cabinet'
      preLoaderRoute: typeof CabinetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rides': {
      id: '/rides'
      path: '/rides'
      fullPath: '/rides'
      preLoaderRoute: typeof RidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$matchId': {
      id: '/order/$matchId'
      path: '/order/$matchId'
      fullPath: '/order/$matchId'
      preLoaderRoute: typeof OrderMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$kind/$id': {
      id: '/listing/$kind/$id'
      path: '/listing/$kind/$id'
      fullPath: '/listing/$kind/$id'
      preLoaderRoute: typeof ListingKindIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CabinetRoute: CabinetRoute,
  ChatsRoute: ChatsRoute,
  CreateRoute: CreateRoute,
  LeaderboardRoute: LeaderboardRoute,
  RidesRoute: RidesRoute,
  OrderMatchIdRoute: OrderMatchIdRoute,
  ListingKindIdRoute: ListingKindIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
